Angellist:
  Enabled: true

Angellist/EnforceMethodCallSites:
  Enabled: true
  Description: "Prevent methods from being called in places you don't allow"
  VersionAdded: "1.1.3"

Angellist/NoUnless:
  Enabled: true
  Description: "Always prefer `if` over `unless`."
  VersionAdded: "1.0.0"

Angellist/PreferDateCurrent:
  Description: "Prefer Date.current over Time.zone.today"
  Enabled: true
  VersionAdded: "1.0.2"

Angellist/ForbidInstanceVariableGetSet:
  Description: "Forbids the use of instance_variable_get and instance_variable_set"
  Enabled: false
  VersionAdded: "1.0.3"

Angellist/ClassStructure:
  Description: "Enforces strict class ordering (built ontop of Layout::ClassStructure)"
  Enabled: true
  VersionAdded: "1.0.4"
  Severity: warning
  ExpectedOrder:
    - module_inclusion
    - graphql_object_types
    - constants
    - nested_classes
    - public_class_methods
    - graphql_fields
    - public_methods
    - protected_methods
    - private_methods
  Categories:
    module_inclusion:
      - extend
      - include
      - prepend
    graphql_object_types:
      - object_type
    constants:
      - casgn
    graphql_fields:
      - implements
      - field
    nested_classes:
      - class
      - module
    public_class_methods:
      - sclass
    public_methods:
      - def
    protected_methods:
      - protected
    private_methods:
      - private
